version: "3.7"

services:
  gluster1:
    build: .
    hostname: node1
    networks:
      nodes:
        aliases:
          - "node1"

  gluster2:
    build: .
    image: homecentr/gluster
    hostname: "node2"
    networks:
      nodes:
        aliases:
          - "node2"

  gluster3:
    build: .
    image: homecentr/gluster
    hostname: "node3"
    networks:
      nodes:
        aliases:
          - "node3"      

networks:
  nodes:
    driver: bridge
    attachable: true